[build]
  command = "npm install && npm run build"  # Install dependencies and then build the project
  publish = "dist"  # Replace with your output directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
